title: "Start Page"
subtitle: "The Dupuis Family"
icon: "fas fa-bullseye"

header: true
footer: '<p>Release 21.09.2 // Contents: Dec 6 2021 8:21 AM EST \\ Created with <span class="has-text-danger">❤️</span> with <a href="https://github.com/bastienwirtz/homer" target="_blank">Homer</a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "white"

# Optional message
#message:
  #url: https://b4bz.io
  #style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #title: "Demo !"
  #icon: "fa fa-grin"
  #content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "News"
    icon: "fas fa-newspaper"
    url: "https://news.google.com"
    target: "_blank" # optional html a tag target attribute
  - name: "Weather"
    icon: "fas fa-umbrella"
    url: "https://forecast.weather.gov/MapClick.php?lat=40.54119500000007&lon=-74.36560999999995"
    target: "_blank" # optional html a tag target attribute
  - name: "Wikipedia"
    icon: "fas fa-atlas"
    url: "https://www.wikipedia.org"
    target: "_blank" # optional html a tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:

  - name: "Family"
    icon: "fas fa-child"
    items:
      - name: "Email"
        logo: "assets/other-icons/zoho.png"
        subtitle: "Zoho"
        tag: "Internet"
        url: "https://accounts.zoho.com/signin?servicename=VirtualOffice"
        target: "_blank" # optional html a tag target attribute
      - name: "Email"
        logo: "assets/walkxcode-icons/png/google-mail.png"
        subtitle: "Google"
        tag: "Internet"
        url: "https://accounts.google.com/AccountChooser/signinchooser?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&flowName=GlifWebSignIn&flowEntry=AccountChooser"
        target: "_blank" # optional html a tag target attribute
      - name: "Drive"
        logo: "assets/other-icons/google-drive.png"
        subtitle: "Google"
        tag: "Internet"
        url: "https://accounts.google.com/ServiceLogin?service=wise&passive=true&continue=http%3A%2F%2Fdrive.google.com%2F%3Futm_source%3Den&utm_medium=button&utm_campaign=web&utm_content=gotodrive&usp=gtd&ltmpl=drive"
        target: "_blank" # optional html a tag target attribute
      - name: "Library"
        logo: "assets/other-icons/libib.png"
        subtitle: "Libib"
        tag: "Internet"
        url: "https://dupuik.libib.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Photos"
        logo: "assets/walkxcode-icons/png/photoprism.png"
        subtitle: "PhotoPrism"
        url: "http://photos:2342"
        target: "_blank" # optional html a tag target attribute

  - name: "Gifts"
    icon: "fas fa-gift"
    items:
      - name: "Calvin"
        logo: "assets/other-icons/ugift.png"
        subtitle: "Ugift 529 Plan"
        tag: "Internet"
        url: "https://www.ugift529.com/gifttpl/ugift/create/viewGiftCodeDetails.cs?ugiftcode=Q42-J0E"
        target: "_blank" # optional html a tag target attribute
      - name: "Julien"
        logo: "assets/other-icons/ugift.png"
        subtitle: "Ugift 529 Plan"
        tag: "Internet"
        url: "https://www.ugift529.com/gifttpl/ugift/create/viewGiftCodeDetails.cs?ugiftcode=J2J-L3M"
        target: "_blank" # optional html a tag target attribute
      - name: "Tara"
        logo: "assets/walkxcode-icons/png/amazon.png"
        subtitle: "Amazon"
        tag: "Internet"
        url: "https://www.amazon.com/hz/wishlist/ls/WO1CF0JNGHHO"
        target: "_blank" # optional html a tag target attribute
      - name: "Ken"
        logo: "assets/walkxcode-icons/png/amazon.png"
        subtitle: "Amazon"
        tag: "Internet"
        url: "https://www.amazon.com/hz/wishlist/ls/2UMH4B2C3MSTQ"
        target: "_blank" # optional html a tag target attribute

  - name: "Information"
    icon: "fas fa-info"
    items:
      - name: "COVID-19"
        logo: "assets/other-icons/coronavirus.jpg"
        subtitle: "kjtd.net"
        tag: "Internet"
        url: "http://covid19.kjtd.net"
        target: "_blank" # optional html a tag target attribute
      - name: "Public Service Announcements"
        icon: "fas fa-exclamation"
        subtitle: "kjtd.net"
        tag: "Internet"
        url: "https://www.kjtd.net/psa"
        target: "_blank" # optional html a tag target attribute
      - name: "Weather Conditions"
        logo: "assets/other-icons/davis.png"
        subtitle: "Davis Vantage Pro2"
        tag: "Internet"
        url: "https://www.wunderground.com/dashboard/pws/KNJMETUC7"
        target: "_blank" # optional html a tag target attribute
      - name: "Weather Radar"
        logo: "assets/other-icons/windy.png"
        subtitle: "Windy.com"
        tag: "Internet"
        url: "https://www.windy.com/-Weather-radar-radar?radar,40.064,-74.363,8,m:eMJad5e"
        target: "_blank" # optional html a tag target attribute

  - name: "Conference"
    icon: "fas fa-compress-arrows-alt"
    items:
      - name: "Video"
        logo: "assets/other-icons/freeconferencecall.jpg"
        subtitle: "FreeConferenceCall"
        tag: "Internet"
        url: "https://www.freeconferencecall.com/wall/dfam"
        target: "_blank" # optional html a tag target attribute
      - name: "Video"
        logo: "assets/walkxcode-icons/png/jitsimeet.png"
        subtitle: "Jitsi"
        tag: "Internet"
        url: "https://meet.jit.si/dfam"
        target: "_blank" # optional html a tag target attribute

  - name: "Infrastructure"
    icon: "fas fa-expand-arrows-alt"
    items:
      - name: "OTA TV Tuner"
        logo: "assets/walkxcode-icons/png/hdhomerun.png"
        subtitle: "HDHomeRun"
        url: "http://HDHR-10612879"
        target: "_blank" # optional html a tag target attribute
      - name: "Storage"
        logo: "assets/walkxcode-icons/png/synology-dsm.png"
        subtitle: "Synology"
        url: "https://vangogh:5001"
        target: "_blank" # optional html a tag target attribute
      - name: "Uninterruptible Power Supply"
        logo: "assets/other-icons/apc.png"
        subtitle: "APC"
        url: "http://ampere"
        target: "_blank" # optional html a tag target attribute

  - name: "Mirrors"
    icon: "fas fa-copy"
    items:
      - name: "AFS at RPI"
        logo: "assets/other-icons/rpi.png"
        subtitle: "Michael Sofka"
        tag: "Internet"
        url: "https://www.kjtd.net/mirrors/homepages.rpi.edu/sofkam"
        target: "_blank" # optional html a tag target attribute
      - name: "IEGMC"
        icon: "fas fa-gamepad"
        subtitle: "kjtd.net"
        tag: "Internet"
        url: "http://iegmc.kjtd.net"
        target: "_blank" # optional html a tag target attribute

  - name: "Network - Access Points"
    icon: "fas fa-wifi"
    items:
      - name: "Wireless Network"
        logo: "assets/walkxcode-icons/png/hp.png"
        subtitle: "Aruba Instant On"
        tag: "Internet"
        url: "https://portal.arubainstanton.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Wireless Network"
        logo: "assets/other-icons/cisco.png"
        subtitle: "Cisco Business"
        url: "http://ciscobusiness.cisco"
        target: "_blank" # optional html a tag target attribute

  - name: "Network - MoCA"
    icon: "fas fa-route"
    items:
      - name: "Playroom"
        logo: "assets/other-icons/gocoax.jpg"
        subtitle: "goCoax"
        url: "http://sylvester"
        target: "_blank" # optional html a tag target attribute
      - name: "Basement"
        logo: "assets/other-icons/gocoax.jpg"
        subtitle: "goCoax"
        url: "http://foghorn"
        target: "_blank" # optional html a tag target attribute
      - name: "Guest Bedroom"
        logo: "assets/other-icons/gocoax.jpg"
        subtitle: "goCoax"
        url: "http://marvin"
        target: "_blank" # optional html a tag target attribute
      - name: "Master Bedroom"
        logo: "assets/other-icons/gocoax.jpg"
        subtitle: "goCoax"
        url: "http://elmer"
        target: "_blank" # optional html a tag target attribute

  - name: "Network - Routers"
    icon: "fas fa-network-wired"
    items:
      - name: "Core"
        logo: "assets/walkxcode-icons/png/pfsense.png"
        subtitle: "pfSense"
        url: "https://morse"
        target: "_blank" # optional html a tag target attribute

  - name: "Network - Switches"
    icon: "fas fa-random"
    items:
      - name: "Core"
        logo: "assets/other-icons/cisco.png"
        subtitle: "Cisco 3560"
        url: "http://watson"
        target: "_blank" # optional html a tag target attribute
      - name: "Basement Office"
        logo: "assets/walkxcode-icons/png/hp.png"
        subtitle: "HP OfficeConnect 1910-8G"
        url: "http://minnie"
        target: "_blank" # optional html a tag target attribute
      - name: "Family Room East"
        logo: "assets/walkxcode-icons/png/hp.png"
        subtitle: "HP OfficeConnect 1910-8G"
        url: "http://donald"
        target: "_blank" # optional html a tag target attribute
      - name: "Family Room West"
        logo: "assets/walkxcode-icons/png/hp.png"
        subtitle: "HP OfficeConnect 1910-8G"
        url: "http://pluto"
        target: "_blank" # optional html a tag target attribute
      - name: "Guest Bedroom"
        logo: "assets/walkxcode-icons/png/hp.png"
        subtitle: "HP OfficeConnect 1910-8G"
        url: "http://jerry"
        target: "_blank" # optional html a tag target attribute
      - name: "Master Bedroom"
        logo: "assets/walkxcode-icons/png/hp.png"
        subtitle: "HP OfficeConnect 1910-8G"
        url: "http://mickey"
        target: "_blank" # optional html a tag target attribute
      - name: "Playroom"
        logo: "assets/walkxcode-icons/png/hp.png"
        subtitle: "HP OfficeConnect 1910-8G"
        url: "http://tom"
        target: "_blank" # optional html a tag target attribute

  - name: "Printers"
    icon: "fas fa-print"
    items:
      - name: "Basement Office"
        logo: "assets/other-icons/brother.jpg"
        subtitle: "Brother MFC-L2710DW"
        url: "http://BRNB4220010ED40"
        target: "_blank" # optional html a tag target attribute
      - name: "Family Room"
        logo: "assets/walkxcode-icons/png/hp.png"
        subtitle: "HP LaserJet Pro MFP M127fn"
        url: "http://cezanne"
        target: "_blank" # optional html a tag target attribute
      - name: "Master Bedroom"
        logo: "assets/other-icons/xerox.jpg"
        subtitle: "Xerox WorkCentre 6515DN MFP"
        url: "http://gauguin"
        target: "_blank" # optional html a tag target attribute

  - name: "Utilities"
    icon: "fas fa-tools"
    items:
      - name: "Media"
        logo: "assets/walkxcode-icons/png/jellyfin.png"
        subtitle: "Jellyfin"
        url: "http://jellyfin:8096"
        target: "_blank" # optional html a tag target attribute
      - name: "Monitor"
        logo: "assets/other-icons/uptimerobot.png"
        subtitle: "UptimeRobot"
        tag: "Internet"
        url: "https://stats.uptimerobot.com/kOJRjCnol7"
        target: "_blank" # optional html a tag target attribute
      - name: "Speed Test"
        logo: "assets/walkxcode-icons/png/librespeed.png"
        subtitle: "LibreSpeed"
        url: "http://kilohertz:8888"
        target: "_blank" # optional html a tag target attribute
      - name: "Speed Test"
        logo: "assets/other-icons/optimum.jpg"
        subtitle: "Optimum"
        tag: "Internet"
        url: "https://www.optimum.com/internet/speed-test"
        target: "_blank" # optional html a tag target attribute
      - name: "Torrents"
        logo: "assets/walkxcode-icons/png/transmission.png"
        subtitle: "Transmission"
        url: "http://godzilla:9091"
        target: "_blank" # optional html a tag target attribute
      - name: "URL Shortener"
        logo: "assets/walkxcode-icons/png/yourls.png"
        subtitle: "YOURLS"
        url: "https://k32.one"
        target: "_blank" # optional html a tag target attribute

  - name: "Virtual Machines"
    icon: "fas fa-server"
    items:
      - name: "godzilla"
        logo: "assets/walkxcode-icons/png/portainer.png"
        subtitle: "Portainer"
        url: "http://godzilla:9000"
        target: "_blank" # optional html a tag target attribute
      - name: "hertz"
        logo: "assets/walkxcode-icons/png/proxmox.png"
        subtitle: "Proxmox"
        url: "https://hertz:8006"
        target: "_blank" # optional html a tag target attribute
      - name: "kilohertz"
        logo: "assets/walkxcode-icons/png/portainer.png"
        subtitle: "Portainer"
        url: "http://kilohertz:9000"
        target: "_blank" # optional html a tag target attribute
      - name: "nimbus"
        logo: "assets/walkxcode-icons/png/portainer.png"
        subtitle: "Portainer"
        url: "http://nimbus:9000"
        target: "_blank" # optional html a tag target attribute

  - name: "nimbus"
    icon: ""
    items:
      - name: "Looking Glass"
        logo: "assets/other-icons/bird.png"
        subtitle: "Bird"
        tag: "Internet"
        url: "http://lg.kjtd.net"
        target: "_blank" # optional html a tag target attribute
      - name: "Speed Test"
        logo: "assets/walkxcode-icons/png/librespeed.png"
        subtitle: "LibreSpeed"
        tag: "Internet"
        url: "http://lg.kjtd.net:8888"
        target: "_blank" # optional html a tag target attribute
