title: "Dupuis Family"
subtitle: "Start Page"
icon: "fas fa-bullseye"

header: true
footer: '<p>Release 22.02.2 // Contents: Jan 13 2024 7:21 PM EDT \\ Created with <span class="has-text-danger">❤️</span> with <a href="https://github.com/bastienwirtz/homer" target="_blank">Homer</a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "white"

# Optional message
#message:
  #url: https://b4bz.io
  #style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  #title: "Demo !"
  #icon: "fa fa-grin"
  #content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "News"
    icon: "fas fa-newspaper"
    url: "https://news.google.com"
    target: "_blank" # optional html a tag target attribute
  - name: "Weather"
    icon: "fas fa-umbrella"
    url: "https://forecast.weather.gov/MapClick.php?lat=40.54119500000007&lon=-74.36560999999995"
    target: "_blank" # optional html a tag target attribute
  - name: "Wikipedia"
    icon: "fas fa-atlas"
    url: "https://en.wikipedia.org/wiki/Main_Page"
    target: "_blank" # optional html a tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:

  - name: "Gifts"
    icon: "fas fa-gift"
    items:
      - name: "Calvin"
        logo: "assets/other-icons/ugift.png"
        subtitle: "Ugift 529 Plan"
        tag: "Internet"
        url: "https://www.ugift529.com/gifttpl/ugift/create/viewGiftCodeDetails.cs?ugiftcode=Q42-J0E"
        target: "_blank" # optional html a tag target attribute
      - name: "Julien"
        logo: "assets/other-icons/ugift.png"
        subtitle: "Ugift 529 Plan"
        tag: "Internet"
        url: "https://www.ugift529.com/gifttpl/ugift/create/viewGiftCodeDetails.cs?ugiftcode=J2J-L3M"
        target: "_blank" # optional html a tag target attribute

  - name: "Family"
    icon: "fas fa-people-roof"
    items:
      - name: "Files"
        icon: "fa-solid fa-file"
        subtitle: "Google Drive"
        tag: "Internet"
        url: "https://drive.google.com/drive/folders/14F5WXHDWEQ-GpmySB7zJY9B1OMejtC7n?usp=drive_link"
        target: "_blank" # optional html a tag target attribute
      - name: "Library"
        icon: "fas fa-book"
        subtitle: "Home"
        tag: "Internet"
        url: "https://www.libib.com/u/dupuik"
        target: "_blank" # optional html a tag target attribute
        
  - name: "Weather"
    icon: "fas fa-tornado"
    items:
      - name: "Weather Conditions"
        logo: "assets/other-icons/davis.png"
        subtitle: "Davis Vantage Pro2"
        tag: "Internet"
        url: "https://www.wunderground.com/dashboard/pws/KNJMETUC7"
        target: "_blank" # optional html a tag target attribute
      - name: "Weather Radar"
        logo: "assets/other-icons/windy.png"
        subtitle: "Windy.com"
        tag: "Internet"
        url: "https://www.windy.com/-Weather-radar-radar?radar,40.064,-74.363,8,m:eMJad5e"
        target: "_blank" # optional html a tag target attribute
      - name: "Merry Sky"
        icon: "fas fa-umbrella"
        tag: "Internet"
        url: "https://merrysky.net/forecast/metuchen%20nj/us"
        target: "_blank" # optional html a tag target attribute
